apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudprober.fullname" . }}
  labels:
    {{- include "cloudprober.labels" . | nindent 4 }}
data:
  config: |
    {{- (tpl .Values.config $)  | nindent 4 }}
